### ISSUE TITLE
link to dead typeform in https://phylax.systems/company

### ISSUE THREAD

**Issue by aatifsyed** [phylaxsystems/phylax.watch#5]
![image](https://github.com/user-attachments/assets/d6e24aaf-1358-4dac-a76a-d898e1752a2c)

Takes you here:

![image](https://github.com/user-attachments/assets/5a32acd2-fcf8-47d1-878c-a05aa01bae12)

**Comment by hylcore-V** [comment]
Does it still need to solve this issue?
